### ISSUE TITLE
Fish Net

### ISSUE THREAD

**Issue by Anmishc** [kevintr303/UnitySteamMultiplayerSample#1]
Hi Kevin, I really liked what you did, you clearly have a knack for this. But I have a question, the thing is that if I use your code and want to add a player to a Game Scene in 2D Game, I can't do it, because FishNet creates the user in the scene where the NetworkManager is located.

I wanted to ask you how to do it? I'm just new to this and would like to know how to do it.

Thank you for your reply. If anything, you can contact me at zaporojec070698@gmail.com or on telegram: @anmishc if you can't reply here.

**Comment by kevintr303** [comment]
> Hi Kevin, I really liked what you did, you clearly have a knack for this. But I have a question, the thing is that if I use your code and want to add a player to a Game Scene in 2D Game, I can't do it, because FishNet creates the user in the scene where the NetworkManager is located.
> 
> I wanted to ask you how to do it? I'm just new to this and would like to know how to do it.
> 
> Thank you for your reply. If anything, you can contact me at [zaporojec070698@gmail.com](mailto:zaporojec070698@gmail.com) or on telegram: @Anmishc if you can't reply here.

Hello! 

Thank you for your interest in my repository. I’m glad you liked the project, and I’ll do my best to address your question.

Due to the way the scenes and networking is currently set up, we need to use the PlayerSpawner script on the Network Manager to spawn a "Client" object for every player. 

Now, if you want to spawn your own player, you would need to spawn each player manually. If you open up the PlayerSpawner script from Fish-Net, you can actually see that the logic for spawning networked objects is quite simple:
```
NetworkObject nob = _networkManager.GetPooledInstantiated(_playerPrefab, position, rotation, true);
_networkManager.ServerManager.Spawn(nob, conn);
```

Here, `conn` is a NetworkConnection object. When we start the game, or when a new player joins, we need to spawn a new player prefab for that specific player (each player has a unique NetworkConnection). 

Here is a sample script (you can place this in any object in the GameScene):
```
using FishNet;
using FishNet.Connection;
using FishNet.Object;
using UnityEngine;

public class PlayerSpawner : MonoBehaviour
{
    [SerializeField] private NetworkObject _playerPrefab;

    private void Awake() 
    {
        foreach (NetworkConnection conn in InstanceFinder.ServerManager.Clients.Values)
        {
            if (conn != null)
            {
                NetworkObject nob = InstanceFinder.NetworkManager.GetPooledInstantiated(
                    prefab: _playerPrefab,
                    position: Vector3.zero,
                    rotation: Quaternion.identity,
                    asServer: true
                );

                InstanceFinder.ServerManager.Spawn(nob, conn);
            }
        }
    }
}
```

If you need to handle when a new player joins the server, you can subscribe to the OnClientPresenceChangeEnd:
```
InstanceFinder.SceneManager.OnClientPresenceChangeEnd += OnClientPresenceChangeEnd;

...
...

private void OnClientPresenceChangeEnd(ClientPresenceChangeEventArgs args)
{
    if (args.Added) { // Added is True if being added to the scene, False if being removed from the scene
        NetworkConnection conn = args.Connection;
        // spawn player conn as before
    }
}
```

Finally, make sure you add any prefabs that you intend to spawn networked to the SpawnablePrefabs asset in the assets root directory.

Let me know if you have any additional questions!
